import {debugEnabled} from '../config/debug.js';
const enabled=debugEnabled('diagnostics');
const history=[];let lastError=null,lastPromise=null,contextState='2d-active';
const push=(type,data={})=>{if(!enabled)return;history.push({at:performance.now(),type,...data});if(history.length>50)history.shift()};
if(enabled){addEventListener('error',event=>{lastError={message:event.message,stack:event.error?.stack};push('javascript-error',lastError)});addEventListener('unhandledrejection',event=>{lastPromise={message:String(event.reason?.message||event.reason),stack:event.reason?.stack};push('unhandled-rejection',lastPromise)});}
const finite=(value)=>Number.isFinite(Number(value));
export function battleEvent(type,data){push(type,data)}
export function validateBattleState(state){if(!enabled||!state)return[];const failures=[];const check=(path,value)=>{if(!finite(value))failures.push({path,value:String(value)})};check('time',state.time);check('hp',state.hp);check('essence',state.essence);for(const [group,list] of Object.entries({enemies:state.enemies,towers:state.towers,shots:state.shots,particles:state.particles})){for(let i=0;i<(list||[]).length;i++){const item=list[i];for(const key of ['x','y','life','hp','t','prog'])if(item[key]!=null)check(`${group}[${i}].${key}`,item[key])}}if(failures.length)push('non-finite-state',{failures});return failures}
export function markContext(state){contextState=state;push(state)}
export function diagnosticSnapshot(state,extra={}){return {stage:state?.chapter?.number,wave:state?.wave,elapsed:state?.time,fps:extra.fps,frameTime:extra.frameTime,enemies:state?.enemies?.length||0,towers:state?.towers?.length||0,projectiles:state?.shots?.length||0,particles:state?.particles?.length||0,roadSegments:state?.routes?.map(route=>route.length)||[],spawnRoutes:state?.routes?.length||0,essence:state?.essence,draft:{open:state?.draftOpen,completed:state?.draftsCompleted},boss:!!state?.boss,shadow:state?.hero&&{x:state.hero.x,y:state.hero.y,hp:state.hero.hp},cathedralHp:state?.hp,renderer:{type:'canvas-2d',contextState},memory:performance.memory&&{used:performance.memory.usedJSHeapSize,total:performance.memory.totalJSHeapSize},lastError,lastPromise,history:[...history],...extra}}
export function installCanvasDiagnostics(canvas){if(!enabled)return;canvas.addEventListener('contextlost',event=>{markContext('2d-context-lost');event.preventDefault?.()});canvas.addEventListener('contextrestored',()=>markContext('2d-context-restored'))}
