begin;

create table if not exists public.tester_feedback (
  id bigint generated by default as identity primary key,
  client_submission_id uuid not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  submission_type text not null check (submission_type in ('bug', 'suggestion', 'general')),
  title text not null check (char_length(title) between 1 and 140),
  description text not null check (char_length(description) between 1 and 8000),
  game_version text not null,
  current_chapter text,
  current_screen text,
  device_info jsonb not null default '{}'::jsonb,
  contact_email text,
  client_submitted_at timestamptz not null,
  submitted_at timestamptz not null default now(),
  steps_to_reproduce text,
  expected_result text,
  actual_result text,
  severity text check (severity is null or severity in ('low', 'medium', 'high', 'critical')),
  client_errors jsonb not null default '[]'::jsonb,
  review_status text not null default 'new' check (review_status in ('new', 'reviewing', 'planned', 'resolved', 'closed')),
  admin_notes text,
  constraint bug_details_required check (
    submission_type <> 'bug' or (
      nullif(trim(steps_to_reproduce), '') is not null and
      nullif(trim(expected_result), '') is not null and
      nullif(trim(actual_result), '') is not null and
      severity is not null
    )
  )
);

create index if not exists tester_feedback_queue_idx
  on public.tester_feedback (review_status, submitted_at desc);
create index if not exists tester_feedback_type_idx
  on public.tester_feedback (submission_type, submitted_at desc);
create index if not exists tester_feedback_severity_idx
  on public.tester_feedback (severity, submitted_at desc)
  where severity is not null;

alter table public.tester_feedback enable row level security;

revoke all on table public.tester_feedback from anon;
revoke all on table public.tester_feedback from authenticated;
grant insert on table public.tester_feedback to authenticated;
grant usage, select on sequence public.tester_feedback_id_seq to authenticated;

drop policy if exists "Authenticated users can submit own feedback" on public.tester_feedback;
create policy "Authenticated users can submit own feedback"
on public.tester_feedback
for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- Deliberately no SELECT, UPDATE, or DELETE policies are created for players.
-- Project administrators can review and manage this table through the
-- Supabase Dashboard/Table Editor, which uses privileged server-side access.

commit;
